FROM debian:12

# Mettre à jour les sources et installer les dépendances pour compiler Python
RUN apt update --allow-releaseinfo-change && apt install -y \
    git build-essential zlib1g-dev libssl-dev libncurses5-dev libgdbm-dev \
    libnss3-dev libreadline-dev libffi-dev curl libsqlite3-dev libbz2-dev

# Supprimer les fichiers inutiles après l'installation
RUN rm -rf /var/lib/apt/lists/*

# Télécharger et compiler Python 3.13
WORKDIR /usr/src
RUN curl -O https://www.python.org/ftp/python/3.13.0/Python-3.13.0.tgz && \
    tar -xf Python-3.13.0.tgz && \
    cd Python-3.13.0 && \
    ./configure --enable-optimizations && \
    make -j$(nproc) && \
    make altinstall && \
    rm -rf /usr/src/Python-3.13.0*

# Vérifier l'installation de Python
RUN python3.13 --version

# Installer les dépendances pour l'affichage distant
RUN apt update && apt install -y \
    x11vnc xvfb fluxbox novnc websockify

# Nettoyage final
RUN rm -rf /var/lib/apt/lists/*

# Créer un dossier pour l'application
WORKDIR /app

# Script de mise à jour et démarrage
RUN echo '#!/bin/bash\n\
cd /app\n\
if [ ! -d ".git" ]; then\n\
  git clone https://github.com/NoobToSayajin/Harverster.git .\n\
else\n\
  git pull\n\
fi\n\
python3.13 -m venv .venv\n\
source .venv/bin/activate\n\
pip install --no-cache-dir -r requirements\n\
Xvfb :0 -screen 0 1920x1080x16 &\n\
fluxbox &\n\
x11vnc -display :0 -nopw -forever &\n\
websockify --web /usr/share/novnc/ 5901 localhost:5900 &\n\
python3.13 app.py' > /start.sh

RUN chmod +x /start.sh

# Exécuter le script au démarrage du conteneur
CMD ["/bin/bash", "/start.sh"]
